server:
  port: 8081

spring:
  datasource:
      url: jdbc:mysql://192.168.1.140:3306/ppfdb_dev?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: dev
      password: dev@aek.com
      driver-class-name: com.mysql.jdbc.Driver

